const route = require("express").Router()
const authorization = require("../../middlewares/authntication")
const validationFunc = require("../../middlewares/valdationFunc")
const accountStatusF = require("./controllers/accountStuts")
const configrationUSer = require("./controllers/configrationUser")
const confirmed = require("./controllers/confirmed")
const signUp = require("./controllers/register")
const signIn = require("./controllers/signIn")
const userEndPoint = require("./endPoint")
const accountStatusValidation = require("./validation/accountStatus")
const configrationUSerValidation = require("./validation/configrationUser")
const signInValidition = require("./validation/signIn")
const signUpValidtion = require("./validation/signUp")

route.post("/signUp",validationFunc(signUpValidtion),signUp)
route.post("/signIn",validationFunc(signInValidition),signIn)
route.get("/user/confirmed/:token",confirmed)
route.patch("/user/configration/",authorization(userEndPoint.configration),validationFunc(configrationUSerValidation),configrationUSer)
route.post("/admin/changeStatus/",authorization(userEndPoint.accountStatusE),validationFunc(accountStatusValidation),accountStatusF)
module.exports = route