const route = require("express").Router()
const authorization = require("../../middlewares/authntication")
const validationFunc = require("../../middlewares/valdationFunc")
const upload = require("../../public/controllers/multerFunctions")
const addComment = require("./controllers/addComment")
const addPost = require("./controllers/addPost")
const deletePost = require("./controllers/deletePost")
const getAllPost = require("./controllers/getAllPost")
const getUserPosts = require("./controllers/getUserPost")
const likePost = require("./controllers/likePost")
const updatePost = require("./controllers/updatePost")
const postEndPoint = require("./endPoint")
const addCommentValid = require("./validation/addComment")
const addPostValidation = require("./validation/addPostValid")
const deletePostValidation = require("./validation/deletePostvalid")
const getPost = require("./validation/getPostValid")
const likePostValid = require("./validation/likePostValid")
const updatePostValid = require("./validation/updatePostValid")

route.post("/post/addPost",authorization(postEndPoint.addPost),upload.array("postPic"),validationFunc(addPostValidation),addPost)
route.delete("/post/deletePost/:id",authorization(postEndPoint.deletePost),validationFunc(deletePostValidation),deletePost)
route.patch("/post/updatePost/:id",authorization(postEndPoint.updatePost),upload.array("updatePic"),validationFunc(updatePostValid),updatePost)
route.patch("/post/like/:id",authorization(postEndPoint.like),validationFunc(likePostValid),likePost)
route.get("/post/getAllPost",validationFunc(getPost),getAllPost)
route.get("/user/getAllPost",authorization(postEndPoint.getPost),validationFunc(getPost),getUserPosts)
route.post("/comment/addComment",authorization(postEndPoint.addComment),validationFunc(addCommentValid),addComment)

module.exports = route