const route = require("express").Router()
const authorization = require("../../middlewares/authntication")
const validationFunc = require("../../middlewares/valdationFunc")
const upload = require("../../public/controllers/multerFunctions")
const addComment = require("./controllers/addComment")
const addPost = require("./controllers/addPost")
const addReply = require("./controllers/addReply")
const deleteComment = require("./controllers/deleteComment")
const deletePost = require("./controllers/deletePost")
const deleteReply = require("./controllers/deleteReply")
const getAllPost = require("./controllers/getAllPost")
const getComment = require("./controllers/getComment")
const getUserPosts = require("./controllers/getUserPost")
const likePost = require("./controllers/likePost")
const updateComment = require("./controllers/updateComment")
const updatePost = require("./controllers/updatePost")
const updateReply = require("./controllers/updateReply")
const postEndPoint = require("./endPoint")
const addCommentValid = require("./validation/addComment")
const addPostValidation = require("./validation/addPostValid")
const addReplyValid = require("./validation/addReplyValid")
const deleteCommentValid = require("./validation/deleteCommentvalid")
const deletePostValidation = require("./validation/deletePostvalid")
const deleteReplyValid = require("./validation/deleteReplyvalid")
const getCommnetvalid = require("./validation/getComment")
const getPost = require("./validation/getPostValid")
const likePostValid = require("./validation/likePostValid")
const updateCommentValid = require("./validation/updateCommentValid")
const updatePostValid = require("./validation/updatePostValid")
const updateReplyValid = require("./validation/updateReplyValid")

route.post("/post/addPost",authorization(postEndPoint.addPost),upload.array("postPic"),validationFunc(addPostValidation),addPost)
route.delete("/post/deletePost/:id",authorization(postEndPoint.deletePost),validationFunc(deletePostValidation),deletePost)
route.patch("/post/updatePost/:id",authorization(postEndPoint.updatePost),upload.array("updatePic"),validationFunc(updatePostValid),updatePost)
route.patch("/post/like/:id",authorization(postEndPoint.like),validationFunc(likePostValid),likePost)
route.get("/post/getAllPost",validationFunc(getPost),getAllPost)
route.get("/user/getAllPost",authorization(postEndPoint.getPost),validationFunc(getPost),getUserPosts)
route.post("/comment/addComment",authorization(postEndPoint.addComment),validationFunc(addCommentValid),addComment)
route.patch("/comment/deleteComment/:idPost/:idComment",authorization(postEndPoint.deleteComment),validationFunc(deleteCommentValid),deleteComment)
route.patch("/comment/updateComment/:idPost/:idComment",authorization(postEndPoint.updateComment),validationFunc(updateCommentValid),updateComment)
route.get("/comment/getComment/:idPost",authorization(postEndPoint.getComment),validationFunc(getCommnetvalid),getComment)
route.post("/reply/addReply/:idPost/:idComment",authorization(postEndPoint.addReply),validationFunc(addReplyValid),addReply)
route.patch("/reply/deleteReply/:idPost/:idComment/:idReply",authorization(postEndPoint.deleteReply),validationFunc(deleteReplyValid),deleteReply)
route.patch("/reply/updateReply/:idPost/:idComment/:idReply",authorization(postEndPoint.updateReply),validationFunc(updateReplyValid),updateReply)

module.exports = route